package my.edu.utem.ftmk.dad.StudentExaminationAttendance.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;


/**
 * This class represents the Academic Staff entity in the database.
 * 
 * 
 * @author atiqaidayu
 * 
 */
@Entity
@Table(name = "academicstaff")
public class AcademicStaff {

    // Primary key for the Academic Staff entity, 
	// auto-generated by the database
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "StaffId")
    private int staffId;

    // Name of the academic staff.
    @Column(name = "StaffName")
    private String name;

    // Phone number of the academic staff.
    @Column(name = "StaffPhoneNo")
    private String phoneNo;

    // Email address of the academic staff.
    @Column(name = "StaffEmail")
    private String email;

    /**
     * Default constructor needed for JPA. 
     * 
     */
    public AcademicStaff() {
    }

    /**
     * Constructor with only staffId provided.
     * @param staffId 
     * The unique identifier for the academic staff.
     * 
     */
    public AcademicStaff(int staffId) {
        this.staffId = staffId;
    }

    /**
     * Constructor with staffId and staffName provided.
     * 
     * @param staffId 
     * The unique identifier for the academic staff.
     * 
     * @param name
     *  The name of the academic staff.
     *  
     */
    public AcademicStaff(int staffId, String name) {
        this.staffId = staffId;
        this.name = name;
    }

    // Getter and Setter methods for class members.

    /**
     * Getter for staffId.
     * @return The unique identifier for the academic staff.
     * 
     */
    public int getStaffId() {
        return staffId;
    }

    /**
     * Setter for staffId.
     * @param staffId 
     * The unique identifier for the academic staff.
     * 
     */
    public void setStaffId(int staffId) {
        this.staffId = staffId;
    }

    /**
     * Getter for staffName.
     * @return The name of the academic staff.
     * 
     */
    public String getStaffName() {
        return name;
    }

    /**
     * Getter for staffPhoneNo.
     * @return The phone number of the academic staff.
     * 
     */
    public String getStaffPhoneNo() {
        return phoneNo;
    }

    /**
     * Setter for staffPhoneNo.
     * @param staffPhoneNo 
     * The phone number of the academic staff.
     * 
     */
    public void setStaffPhoneNo(String staffPhoneNo) {
        this.phoneNo = staffPhoneNo;
    }

    /**
     * Getter for staffEmail.
     * @return The email address of the academic staff.
     */
    public String getStaffEmail() {
        return email;
    }

    /**
     * Setter for staffEmail.
     * @param email 
     * The email address of the academic staff.
     * 
     */
    public void setStaffEmail(String email) {
        this.email = email;
    }
}
