package my.edu.utem.ftmk.dad.StudentExaminationAttendance.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * This class represents the Venue entity in the database.
 * 
 * 
 * @author irdinafarisya
 */
@Entity
@Table(name = "venue")
public class Venue {

    // Primary key for the Venue entity, auto-generated by the database.
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "VenueId")
    private int venueId;

    // Name of the venue
    @Column(name = "VenueName")
    private String name;

    // Capacity of the venue (maximum number of attendees)
    @Column(name = "Capacity")
    private int capacity;

    /**
     * Default constructor for the Venue entity.
     * 
     */
    public Venue() {
        // Initialize any necessary variables or perform other setup tasks
    }

    /**
     * Constructor with only venueId provided.
     * @param venueId 
     * The unique identifier for the venue.
     * 
     */
    public Venue(int venueId) {
        this.venueId = venueId;
    }

    // Getter and Setter methods for class members.

    /**
     * Getter for the venue ID.
     * @return The unique identifier for the venue.
     * 
     */
    public int getVenueId() {
        return venueId;
    }

    /**
     * Setter for the venue ID.
     * @param venueId The unique identifier for the venue.
     * 
     */
    public void setVenueId(int venueId) {
        this.venueId = venueId;
    }

    /**
     * Getter for the name of the venue.
     * @return The name of the venue.
     * 
     */
    public String getVenueName() {
        return name;
    }

    /**
     * Setter for location of venue.
     * @param name 
     * 
     * The location of the venue.
     * 
     */
    public void setVenueName(String name) {
        this.name = name;
    }

    /**
     * Getter for the capacity of the venue.
     * @return The capacity of the venue (maximum number of attendees).
     * 
     */
    public int getCapacity() {
        return capacity;
    }

    /**
     * Setter for the capacity of the venue.
     * @param capacity 
     * The capacity of the venue (maximum number of attendees).
     * 
     */
    public void setCapacity(int capacity) {
        this.capacity = capacity;
    }
}
